### ISSUE TITLE
on Windows

### ISSUE THREAD

**Issue by fr4ncidir** [vaimee/sepatools#9]
Unfortunately, engine doesn't start when I try it on windows

**Comment by lroffia** [comment]
please provide some more details
-------- Messaggio originale --------Da: Francesco Antoniazzi <notifications@github.com> Data: 27/05/17  13:42  (GMT+01:00) A: vaimee/sepatools <sepatools@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: [vaimee/sepatools] on Windows (#9) 
Unfortunately, engine doesn't start when I try it on windows

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vaimee/sepatools","title":"vaimee/sepatools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vaimee/sepatools"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"on Windows (#9)"}],"action":{"name":"View Issue","url":"https://github.com/vaimee/sepatools/issues/9"}}}

**Comment by fr4ncidir** [comment]
There's some strange behaviour in Eclipse... I'm closing the issue because it's probably due to wrong configurations. Sorry :)
